### ISSUE TITLE
Why is this tied to Benefits?

### ISSUE THREAD

**Issue by hapoza** [vtex-apps/product-kit#18]
I have a SKU configured as a Kit Look in Catalog that works fine on CMS with the controllers (productName, skuRichSelection, BuyInPage, skuPrice). Unfortunately, I don't have a public URL of it to share, so here's a sample of what the Search API contains:

```json
    {
      "productName": "Kit Blusa + Tênis",
      "items": [
        {
          "kitItems": [
            {
              "itemId": "201",
              "amount": 10000
            },
            {
              "itemId": "136",
              "amount": 10000
            }
          ]
        }
      ]
    }
```

But visiting the same product on `vtex.dreamstore` with `vtex.product-kit` doesn't work because it's strictly checking for data from Rates&Benefits, [see here](https://github.com/vtex-apps/product-kit/blob/25070ddcd235a9ee7cbb377138fb44d06f29ea31/react/ProductKit.js#L110).

AFAIK, "kit" and "kit look" SKUs don't need to be tied to some kind of discount or promotion. There's two help pages that don't mention any form of configuration on Rates&Benefits:
[Kit registration](http://help.vtex.com/en/tutorial/kit-registration/)
[How to assemble a Kit Look](http://help.vtex.com/en/tutorial/how-to-assemble-a-look-kit)

**Comment by denisebiscaro** [comment]
Solved by - https://vtex.io/docs/components/all/acupula.kitlook
